apiVersion: v1
kind: Service
metadata:
  name: qwen-code-lora-tenant-b
  namespace: default
  labels:
    model.aibrix.ai/name: qwen-code-lora-tenant-b
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    model.aibrix.ai/name: qwen2.5-1.5b-instruct
    adapter.model.aibrix.ai/enabled: "true"
